### ISSUE TITLE
Where to put config file?

### ISSUE THREAD

**Issue by reptile18** [Krizzu/eslint-check-action#11]
Okay, I tried it with a .eslintrc in my project root directory and it worked. 

I tried it with a .eslintrc.json specifying it like this:
```yml
name: Lint
on: [push]
jobs:
  eslint_check:
    name: Prepare action
    runs-on: ubuntu-latest
    steps:
      # Checkout action must run prior to eslint check
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintConfig: "eslintrc.json"
```

and it fails with: 
##[error]Cannot read config file: /github/workspace/eslintrc.json

the .eslintrc.json is in the exact same directory (root).

I also tried "./eslintrc.json"
