### ISSUE TITLE
Invalid request

### ISSUE THREAD

**Issue by averichev** [Krizzu/eslint-check-action#2]
![image](https://user-images.githubusercontent.com/5820708/73071893-fb5e6100-3ec4-11ea-95f8-61dcf6d3e740.png)

with 

```yaml
jobs:
  eslint_check:
    name: prepare
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Lint
      uses: Krizzu/eslint-check-action@v1.0.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintExt: "vue"
        eslintConfig: ".eslintrc.js"
```

file ```.eslintrc.js``` in root of repository
